### ISSUE TITLE
[Crash] Mod §echunkloaders§r requires §6supermartijn642configlib§r §o1.0.9 or above§r §7Currently, §6supermartijn642configlib§r§7 is §o§nnot installed

### ISSUE THREAD

**Issue by B10Reaper** [SuperMartijn642/SuperMartijn642sCoreLib#1]
**Version Info**
- Minecraft, 1.17.1
- Core Lib, 1.0.14

**Steps to Reproduce**
Start server with chunkloader and 1.014, enjoy crash
Start server with chunkloader and 1.9, All is fine

**Crash report (~/logs/latest.log)**
[16:12:19] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 37.0.109, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]
[16:12:19] [main/INFO]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17 by Oracle Corporation
[16:12:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=union:/C:/Users/regro/Desktop/Minecraft%20Server/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar%2318! Service=ModLauncher Env=SERVER
[16:12:20] [main/INFO]: Found mod file 2collective-1.17.1-2.64.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file 2selene-1.17.1-1.10.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file absentbydesign-1.17.1-1.6.0.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file additionallanterns-1.0.0a-mc1.17.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file alexsmobs-1.13.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file bambooeverything-1.1.3-build.6+mc1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file BiomesOPlenty-1.17.1-14.0.0.36-universal.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file buildersaddition-1.17.1-20211105a.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file catalogue-1.4.0-1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file cfm-7.0.0pre25-1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file chunkloaders-1.1.7a-mc1.17.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file citadel-1.9.3-1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file cloth-config-5.0.38-forge.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file configured-1.3.0-1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file CraftingAutomat-MC1.17.1-1.2.2.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file dynviewdist-2.2.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file extendedcreativeinventory_1.17.1-1.6.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file goldenhopper-1.2.4-1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file mcw-lights-1.0.1-mc1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file restored_earth-1.17.1-1.1.0.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file simplyutilities-1.17.1-0.5.2-build.18.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file skinned_lanterns-1.17.1-1.3.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file supermartijn642corelib-1.0.14-mc1.17.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file supplementaries-1.17.1-0.18.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file The_Wild_Update_Mod_V0.7_Minecraft_1.17.1.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file thevanillaexperience_1.17.1-1.4.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:20] [main/INFO]: Found mod file worldedit-mod-7.2.7.jar of type MOD with locator {mods folder locator at C:\Users\regro\Desktop\Minecraft Server\mods}
[16:12:21] [main/INFO]: Found mod file fmlcore-1.17.1-37.0.109.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@12bfd80d
[16:12:21] [main/INFO]: Found mod file javafmllanguage-1.17.1-37.0.109.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@12bfd80d
[16:12:21] [main/INFO]: Found mod file mclanguage-1.17.1-37.0.109.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@12bfd80d
[16:12:21] [main/INFO]: Found mod file server-1.17.1-20210706.113038-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@12bfd80d
[16:12:21] [main/INFO]: Found mod file forge-1.17.1-37.0.109-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@12bfd80d
[16:12:24] [main/INFO]: Launching target 'forgeserver' with arguments []
[16:12:46] [main/FATAL]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §echunkloaders§r requires §6supermartijn642configlib§r §o1.0.9 or above§r
§7Currently, §6supermartijn642configlib§r§7 is §o§nnot installed
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:64) ~[fmlcore-1.17.1-37.0.109.jar%2353!:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:109) ~[fmlcore-1.17.1-37.0.109.jar%2353!:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:141) ~[fmlcore-1.17.1-37.0.109.jar%2353!:?]
	at net.minecraftforge.fmllegacy.server.ServerModLoader.load(ServerModLoader.java:45) ~[forge-1.17.1-37.0.109-universal.jar%2356!:?]
	at net.minecraft.server.Main.main(Main.java:100) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.17.1-37.0.109.jar%2322!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[16:12:47] [main/FATAL]: Crash report saved to .\crash-reports\crash-2021-11-14_16.12.47-fml.txt
[16:12:47] [main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Mod §echunkloaders§r requires §6supermartijn642configlib§r §o1.0.9 or above§r
§7Currently, §6supermartijn642configlib§r§7 is §o§nnot installed
]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:161) ~[fmlcore-1.17.1-37.0.109.jar%2353!:?]
	at net.minecraftforge.fmllegacy.server.ServerModLoader.load(ServerModLoader.java:45) ~[forge-1.17.1-37.0.109-universal.jar%2356!:?]
	at net.minecraft.server.Main.main(Main.java:100) ~[server-1.17.1-20210706.113038-srg.jar%2352!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.17.1-37.0.109.jar%2322!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]

**Comment by SuperMartijn642** [comment]
Yes, as it says, you need to install the config lib. https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib

**Comment by B10Reaper** [comment]
Correct. Now look further down my log where I have the latest version loaded in and it gets rejected. The whole point was it rejects the latest version unless I put .9 in the folder.

**Comment by SuperMartijn642** [comment]
Note that the core and config lib are two separate things. You don't have the config lib installed, only the core lib.
The latest version of the config lib is 1.0.9.

**Comment by B10Reaper** [comment]
I’m embarrassed that I did not notice that. Sorry to bother you!

**Comment by SuperMartijn642** [comment]
No worries, the names are indeed quite similar 🙂

**Comment by Endermanbugzjfc** [comment]
Probably visually disabled people are better at distinguishing these two.
I committed the same mistake. 😓
