### ISSUE TITLE
[Crash] collective-1.20.1-7.84

### ISSUE THREAD

**Issue by Whininie** [SuperMartijn642/SuperMartijn642sCoreLib#67]
**Version Info**
- Minecraft, 1.20.1
- Core Lib, 1.1.17

**Steps to Reproduce**
Filtered mod till the crash. problem is: collective-1.20.1-7.84

**Crash report (~/logs/latest.log)**
[19aug.2024 14:31:32.826] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Whininiee, --version, 1.20.1-forge-47.3.6, --gameDir, C:\Users\Elwin Beekman\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\assets, --assetIndex, 5, --uuid, 9b7f26db88794d26af976c986f417b08, --accessToken, ????????, --clientId, YzY3YmYzNTEtYTRkMy00ODUzLWIzNDctYjA3ZWVhMzk1ZDVk, --xuid, 2535413349772921, --userType, msa, --versionType, release, --quickPlayPath, C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\quickPlay\java\1724070689821.json, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.6, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[19aug.2024 14:31:32.832] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8 by Microsoft; OS Windows 11 arch amd64 version 10.0
[19aug.2024 14:31:33.424] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[19aug.2024 14:31:33.519] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[19aug.2024 14:31:33.889] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[19aug.2024 14:31:34.078] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Elwin%20Beekman/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[19aug.2024 14:31:34.185] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.29, NVIDIA Corporation
[19aug.2024 14:31:34.570] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.6\fmlcore-1.20.1-47.3.6.jar is missing mods.toml file
[19aug.2024 14:31:34.574] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.6\javafmllanguage-1.20.1-47.3.6.jar is missing mods.toml file
[19aug.2024 14:31:34.577] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.6\lowcodelanguage-1.20.1-47.3.6.jar is missing mods.toml file
[19aug.2024 14:31:34.582] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.6\mclanguage-1.20.1-47.3.6.jar is missing mods.toml file
[19aug.2024 14:31:34.886] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 6 dependencies adding them to mods collection
[19aug.2024 14:31:38.097] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[19aug.2024 14:31:38.258] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [de.maxhenkel.camera.MixinConnector]
[19aug.2024 14:31:38.260] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-forge-47.3.6, --gameDir, C:\Users\Elwin Beekman\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\assets, --uuid, 9b7f26db88794d26af976c986f417b08, --username, Whininiee, --assetIndex, 5, --accessToken, ????????, --clientId, YzY3YmYzNTEtYTRkMy00ODUzLWIzNDctYjA3ZWVhMzk1ZDVk, --xuid, 2535413349772921, --userType, msa, --versionType, release, --quickPlayPath, C:\Users\Elwin Beekman\AppData\Roaming\.minecraft\quickPlay\java\1724070689821.json]
[19aug.2024 14:31:38.278] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 41 options available, 3 override(s) found
[19aug.2024 14:31:38.332] [main/WARN] [mixin/]: Reference map 'immersive_paintings-common-refmap.json' for immersive_paintings.mixin.json could not be read. If this is a development environment you can ignore this message
[19aug.2024 14:31:38.566] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:38.567] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:38.568] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:38.568] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:38.569] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:38.579] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:38.580] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:38.581] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[19aug.2024 14:31:39.109] [main/WARN] [mixin/]: Error loading class: me/jellysquid/mods/sodium/client/render/vertex/buffer/SodiumBufferBuilder (java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder)
[19aug.2024 14:31:39.109] [main/WARN] [mixin/]: @Mixin target me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder was not found mixins.oculus.compat.sodium.json:vertex_format.MixinSodiumBufferBuilder
[19aug.2024 14:31:39.402] [main/WARN] [mixin/]: Error loading class: com/copycatsplus/copycats/content/copycat/slab/CopycatSlabBlock (java.lang.ClassNotFoundException: com.copycatsplus.copycats.content.copycat.slab.CopycatSlabBlock)
[19aug.2024 14:31:39.402] [main/WARN] [mixin/]: @Mixin target com.copycatsplus.copycats.content.copycat.slab.CopycatSlabBlock was not found create_connected.mixins.json:compat.CopycatBlockMixin
[19aug.2024 14:31:39.405] [main/WARN] [mixin/]: Error loading class: com/copycatsplus/copycats/content/copycat/board/CopycatBoardBlock (java.lang.ClassNotFoundException: com.copycatsplus.copycats.content.copycat.board.CopycatBoardBlock)
[19aug.2024 14:31:39.405] [main/WARN] [mixin/]: @Mixin target com.copycatsplus.copycats.content.copycat.board.CopycatBoardBlock was not found create_connected.mixins.json:compat.CopycatBlockMixin
[19aug.2024 14:31:39.420] [main/WARN] [mixin/]: Error loading class: me/jellysquid/mods/lithium/common/ai/pathing/PathNodeDefaults (java.lang.ClassNotFoundException: me.jellysquid.mods.lithium.common.ai.pathing.PathNodeDefaults)
[19aug.2024 14:31:39.663] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[19aug.2024 14:31:45.034] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 190 Datafixer optimizations took 228 milliseconds
[19aug.2024 14:31:49.118] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/Elwin%20Beekman/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23218!/assets/.mcassetsroot' uses unexpected schema
[19aug.2024 14:31:49.119] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/Elwin%20Beekman/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23218!/data/.mcassetsroot' uses unexpected schema
[19aug.2024 14:31:49.147] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19aug.2024 14:31:49.678] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Whininiee
[19aug.2024 14:31:49.799] [Render thread/ERROR] [net.minecraft.client.Options/]: Error parsing option value 0 for option Max Framerate: Value 0 outside of range [10:260]
[19aug.2024 14:31:49.814] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[19aug.2024 14:31:49.900] [Render thread/FATAL] [mixin/]: Mixin apply failed mixins.oculus.compat.sodium.json:options.MixinSodiumGameOptions -> me.jellysquid.mods.sodium.client.gui.SodiumGameOptions: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on iris$writeIrisConfig could not find any targets matching 'writeToDisk' in me.jellysquid.mods.sodium.client.gui.SodiumGameOptions. Using refmap sodiumCompatibility-oculus-mixins-refmap.json [PREINJECT Applicator Phase -> mixins.oculus.compat.sodium.json:options.MixinSodiumGameOptions -> Prepare Injections ->  -> handler$zjk000$iris$writeIrisConfig(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on iris$writeIrisConfig could not find any targets matching 'writeToDisk' in me.jellysquid.mods.sodium.client.gui.SodiumGameOptions. Using refmap sodiumCompatibility-oculus-mixins-refmap.json [PREINJECT Applicator Phase -> mixins.oculus.compat.sodium.json:options.MixinSodiumGameOptions -> Prepare Injections ->  -> handler$zjk000$iris$writeIrisConfig(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.GeneratedConstructorAccessor63.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at me.jellysquid.mods.sodium.client.SodiumClientMod.loadConfig(SodiumClientMod.java:53) ~[rubidium-mc1.20.1-0.7.1a.jar%23209!/:?]
	at me.jellysquid.mods.sodium.client.SodiumClientMod.<clinit>(SodiumClientMod.java:22) ~[rubidium-mc1.20.1-0.7.1a.jar%23209!/:?]
	at com.mojang.blaze3d.platform.Window.redirect$zci000$wrapGlfwCreateWindow(Window.java:535) ~[client-1.20.1-20230612.114412-srg.jar%23218!/:?]
	at com.mojang.blaze3d.platform.Window.<init>(Window.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23218!/:?]
	at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23218!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:440) ~[client-1.20.1-20230612.114412-srg.jar%23218!/:?]
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.3.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.6.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.6.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by SuperMartijn642** [comment]
Please explain what the issue is. What does this have to do with my core library?

**Comment by Whininie** [comment]
already fixt it, thanks
